"use strict";
exports.__esModule = true;
var a = require("./a.png");
var corpse_bride_by_singularwish_d5qod9g_jpg_1 = require("../../asserts/images/corpse_bride_by_singularwish-d5qod9g.jpg");
var imgA = document.createElement('img');
var imagB = document.createElement('img');
imgA.src = a;
imagB.src = corpse_bride_by_singularwish_d5qod9g_jpg_1["default"];
document.appendChild(imgA);
document.appendChild(imagB);
